version: "3"

services:
  dnscrypt:
    container_name: dnscrypt-proxy
    image: klutchell/dnscrypt-proxy:latest
    volumes:
      - './volumes/dnscrypt-proxy:/config'
    ports:
      - "53000:53/tcp"
      - "53000:53/udp"
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: jacklul/pihole:latest
    hostname: ${HOSTNAME}
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # DHCP
      - "80:80/tcp"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${WEBPASSWORD}
      PIHOLE_DNS_: ${PIHOLE_DNS}
    volumes:
      - './volumes/pihole:/etc/pihole'
      - './volumes/dnsmasq.d:/etc/dnsmasq.d'
      - './volumes/pihole-updatelists:/etc/pihole-updatelists'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
